// DO NOT EDIT. This was generated by svd2rusty
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
pub mod RCC {
    pub mod cr {
        pub const HSION: u32 = 0;
        pub const HSIRDY: u32 = 1;
        pub const HSITRIM: u32 = 3;
        pub const HSICAL: u32 = 8;
        pub const HSEON: u32 = 16;
        pub const HSERDY: u32 = 17;
        pub const HSEBYP: u32 = 18;
        pub const CSSON: u32 = 19;
        pub const PLLON: u32 = 24;
        pub const PLLRDY: u32 = 25;
    }
    pub mod cfgr {
        pub const SW: u32 = 0;
        pub const SWS: u32 = 2;
        pub const HPRE: u32 = 4;
        pub const PPRE: u32 = 8;
        pub const ADCPRE: u32 = 14;
        pub const PLLSRC: u32 = 15;
        pub const PLLXTPRE: u32 = 17;
        pub const PLLMUL: u32 = 18;
        pub const MCO: u32 = 24;
        pub const MCOPRE: u32 = 28;
        pub const PLLNODIV: u32 = 31;
    }
    pub mod cir {
        pub const LSIRDYF: u32 = 0;
        pub const LSERDYF: u32 = 1;
        pub const HSIRDYF: u32 = 2;
        pub const HSERDYF: u32 = 3;
        pub const PLLRDYF: u32 = 4;
        pub const HSI14RDYF: u32 = 5;
        pub const HSI48RDYF: u32 = 6;
        pub const CSSF: u32 = 7;
        pub const LSIRDYIE: u32 = 8;
        pub const LSERDYIE: u32 = 9;
        pub const HSIRDYIE: u32 = 10;
        pub const HSERDYIE: u32 = 11;
        pub const PLLRDYIE: u32 = 12;
        pub const HSI14RDYE: u32 = 13;
        pub const HSI48RDYIE: u32 = 14;
        pub const LSIRDYC: u32 = 16;
        pub const LSERDYC: u32 = 17;
        pub const HSIRDYC: u32 = 18;
        pub const HSERDYC: u32 = 19;
        pub const PLLRDYC: u32 = 20;
        pub const HSI14RDYC: u32 = 21;
        pub const HSI48RDYC: u32 = 22;
        pub const CSSC: u32 = 23;
    }
    pub mod apb2rstr {
        pub const SYSCFGRST: u32 = 0;
        pub const ADCRST: u32 = 9;
        pub const TIM1RST: u32 = 11;
        pub const SPI1RST: u32 = 12;
        pub const USART1RST: u32 = 14;
        pub const TIM15RST: u32 = 16;
        pub const TIM16RST: u32 = 17;
        pub const TIM17RST: u32 = 18;
        pub const DBGMCURST: u32 = 22;
    }
    pub mod apb1rstr {
        pub const TIM2RST: u32 = 0;
        pub const TIM3RST: u32 = 1;
        pub const TIM6RST: u32 = 4;
        pub const TIM7RST: u32 = 5;
        pub const TIM14RST: u32 = 8;
        pub const WWDGRST: u32 = 11;
        pub const SPI2RST: u32 = 14;
        pub const USART2RST: u32 = 17;
        pub const USART3RST: u32 = 18;
        pub const USART4RST: u32 = 19;
        pub const I2C1RST: u32 = 21;
        pub const I2C2RST: u32 = 22;
        pub const USBRST: u32 = 23;
        pub const CANRST: u32 = 25;
        pub const CRSRST: u32 = 27;
        pub const PWRRST: u32 = 28;
        pub const DACRST: u32 = 29;
        pub const CECRST: u32 = 30;
    }
    pub mod ahbenr {
        pub const DMA1EN: u32 = 0;
        pub const SRAMEN: u32 = 2;
        pub const FLITFEN: u32 = 4;
        pub const CRCEN: u32 = 6;
        pub const IOPAEN: u32 = 17;
        pub const IOPBEN: u32 = 18;
        pub const IOPCEN: u32 = 19;
        pub const IOPDEN: u32 = 20;
        pub const IOPFEN: u32 = 22;
        pub const TSCEN: u32 = 24;
    }
    pub mod apb2enr {
        pub const SYSCFGEN: u32 = 0;
        pub const ADCEN: u32 = 9;
        pub const TIM1EN: u32 = 11;
        pub const SPI1EN: u32 = 12;
        pub const USART1EN: u32 = 14;
        pub const TIM15EN: u32 = 16;
        pub const TIM16EN: u32 = 17;
        pub const TIM17EN: u32 = 18;
        pub const DBGMCUEN: u32 = 22;
    }
    pub mod apb1enr {
        pub const TIM2EN: u32 = 0;
        pub const TIM3EN: u32 = 1;
        pub const TIM6EN: u32 = 4;
        pub const TIM7EN: u32 = 5;
        pub const TIM14EN: u32 = 8;
        pub const WWDGEN: u32 = 11;
        pub const SPI2EN: u32 = 14;
        pub const USART2EN: u32 = 17;
        pub const USART3EN: u32 = 18;
        pub const USART4EN: u32 = 19;
        pub const I2C1EN: u32 = 21;
        pub const I2C2EN: u32 = 22;
        pub const USBRST: u32 = 23;
        pub const CANEN: u32 = 25;
        pub const CRSEN: u32 = 27;
        pub const PWREN: u32 = 28;
        pub const DACEN: u32 = 29;
        pub const CECEN: u32 = 30;
    }
    pub mod bdcr {
        pub const LSEON: u32 = 0;
        pub const LSERDY: u32 = 1;
        pub const LSEBYP: u32 = 2;
        pub const LSEDRV: u32 = 3;
        pub const RTCSEL: u32 = 8;
        pub const RTCEN: u32 = 15;
        pub const BDRST: u32 = 16;
    }
    pub mod csr {
        pub const LSION: u32 = 0;
        pub const LSIRDY: u32 = 1;
        pub const RMVF: u32 = 24;
        pub const OBLRSTF: u32 = 25;
        pub const PINRSTF: u32 = 26;
        pub const PORRSTF: u32 = 27;
        pub const SFTRSTF: u32 = 28;
        pub const IWDGRSTF: u32 = 29;
        pub const WWDGRSTF: u32 = 30;
        pub const LPWRRSTF: u32 = 31;
    }
    pub mod ahbrstr {
        pub const IOPARST: u32 = 17;
        pub const IOPBRST: u32 = 18;
        pub const IOPCRST: u32 = 19;
        pub const IOPDRST: u32 = 20;
        pub const IOPFRST: u32 = 22;
        pub const TSCRST: u32 = 24;
    }
    pub mod cfgr2 {
        pub const PREDIV: u32 = 0;
    }
    pub mod cfgr3 {
        pub const USART1SW: u32 = 0;
        pub const I2C1SW: u32 = 4;
        pub const CECSW: u32 = 6;
        pub const USBSW: u32 = 7;
        pub const ADCSW: u32 = 8;
        pub const USART2SW: u32 = 16;
    }
    pub mod cr2 {
        pub const HSI14ON: u32 = 0;
        pub const HSI14RDY: u32 = 1;
        pub const HSI14DIS: u32 = 2;
        pub const HSI14TRIM: u32 = 3;
        pub const HSI14CAL: u32 = 8;
        pub const HSI48ON: u32 = 16;
        pub const HSI48RDY: u32 = 17;
        pub const HSI48CAL: u32 = 24;
    }
}
pub mod USART {
    pub mod cr1 {
        pub const UE: u32 = 0;
        pub const UESM: u32 = 1;
        pub const RE: u32 = 2;
        pub const TE: u32 = 3;
        pub const IDLEIE: u32 = 4;
        pub const RXNEIE: u32 = 5;
        pub const TCIE: u32 = 6;
        pub const TXEIE: u32 = 7;
        pub const PEIE: u32 = 8;
        pub const PS: u32 = 9;
        pub const PCE: u32 = 10;
        pub const WAKE: u32 = 11;
        pub const M: u32 = 12;
        pub const MME: u32 = 13;
        pub const CMIE: u32 = 14;
        pub const OVER8: u32 = 15;
        pub const DEDT: u32 = 16;
        pub const DEAT: u32 = 21;
        pub const RTOIE: u32 = 26;
        pub const EOBIE: u32 = 27;
        pub const M1: u32 = 28;
    }
    pub mod cr2 {
        pub const ADD4: u32 = 28;
        pub const ADD0: u32 = 24;
        pub const RTOEN: u32 = 23;
        pub const ABRMOD: u32 = 21;
        pub const ABREN: u32 = 20;
        pub const MSBFIRST: u32 = 19;
        pub const DATAINV: u32 = 18;
        pub const TXINV: u32 = 17;
        pub const RXINV: u32 = 16;
        pub const SWAP: u32 = 15;
        pub const LINEN: u32 = 14;
        pub const STOP: u32 = 12;
        pub const CLKEN: u32 = 11;
        pub const CPOL: u32 = 10;
        pub const CPHA: u32 = 9;
        pub const LBCL: u32 = 8;
        pub const LBDIE: u32 = 6;
        pub const LBDL: u32 = 5;
        pub const ADDM7: u32 = 4;
    }
    pub mod cr3 {
        pub const WUFIE: u32 = 22;
        pub const WUS: u32 = 20;
        pub const SCARCNT: u32 = 17;
        pub const DEP: u32 = 15;
        pub const DEM: u32 = 14;
        pub const DDRE: u32 = 13;
        pub const OVRDIS: u32 = 12;
        pub const ONEBIT: u32 = 11;
        pub const CTSIE: u32 = 10;
        pub const CTSE: u32 = 9;
        pub const RTSE: u32 = 8;
        pub const DMAT: u32 = 7;
        pub const DMAR: u32 = 6;
        pub const SCEN: u32 = 5;
        pub const NACK: u32 = 4;
        pub const HDSEL: u32 = 3;
        pub const IRLP: u32 = 2;
        pub const IREN: u32 = 1;
        pub const EIE: u32 = 0;
    }
    pub mod brr {
        pub const DIV_Mantissa: u32 = 4;
        pub const DIV_Fraction: u32 = 0;
    }
    pub mod gtpr {
        pub const GT: u32 = 8;
        pub const PSC: u32 = 0;
    }
    pub mod rtor {
        pub const BLEN: u32 = 24;
        pub const RTO: u32 = 0;
    }
    pub mod rqr {
        pub const TXFRQ: u32 = 4;
        pub const RXFRQ: u32 = 3;
        pub const MMRQ: u32 = 2;
        pub const SBKRQ: u32 = 1;
        pub const ABRRQ: u32 = 0;
    }
    pub mod isr {
        pub const REACK: u32 = 22;
        pub const TEACK: u32 = 21;
        pub const WUF: u32 = 20;
        pub const RWU: u32 = 19;
        pub const SBKF: u32 = 18;
        pub const CMF: u32 = 17;
        pub const BUSY: u32 = 16;
        pub const ABRF: u32 = 15;
        pub const ABRE: u32 = 14;
        pub const EOBF: u32 = 12;
        pub const RTOF: u32 = 11;
        pub const CTS: u32 = 10;
        pub const CTSIF: u32 = 9;
        pub const LBDF: u32 = 8;
        pub const TXE: u32 = 7;
        pub const TC: u32 = 6;
        pub const RXNE: u32 = 5;
        pub const IDLE: u32 = 4;
        pub const ORE: u32 = 3;
        pub const NF: u32 = 2;
        pub const FE: u32 = 1;
        pub const PE: u32 = 0;
    }
    pub mod icr {
        pub const WUCF: u32 = 20;
        pub const CMCF: u32 = 17;
        pub const EOBCF: u32 = 12;
        pub const RTOCF: u32 = 11;
        pub const CTSCF: u32 = 9;
        pub const LBDCF: u32 = 8;
        pub const TCCF: u32 = 6;
        pub const IDLECF: u32 = 4;
        pub const ORECF: u32 = 3;
        pub const NCF: u32 = 2;
        pub const FECF: u32 = 1;
        pub const PECF: u32 = 0;
    }
    pub mod rdr {
        pub const RDR: u32 = 0;
    }
    pub mod tdr {
        pub const TDR: u32 = 0;
    }
}
pub mod FLASH {
    pub mod acr {
        pub const LATENCY: u32 = 0;
        pub const PRFTBE: u32 = 4;
        pub const PRFTBS: u32 = 5;
    }
    pub mod keyr {
        pub const FKEYR: u32 = 0;
    }
    pub mod optkeyr {
        pub const OPTKEYR: u32 = 0;
    }
    pub mod sr {
        pub const EOP: u32 = 5;
        pub const WRPRT: u32 = 4;
        pub const PGERR: u32 = 2;
        pub const BSY: u32 = 0;
    }
    pub mod cr {
        pub const FORCE_OPTLOAD: u32 = 13;
        pub const EOPIE: u32 = 12;
        pub const ERRIE: u32 = 10;
        pub const OPTWRE: u32 = 9;
        pub const LOCK: u32 = 7;
        pub const STRT: u32 = 6;
        pub const OPTER: u32 = 5;
        pub const OPTPG: u32 = 4;
        pub const MER: u32 = 2;
        pub const PER: u32 = 1;
        pub const PG: u32 = 0;
    }
    pub mod ar {
        pub const FAR: u32 = 0;
    }
    pub mod obr {
        pub const OPTERR: u32 = 0;
        pub const RDPRT: u32 = 1;
        pub const WDG_SW: u32 = 8;
        pub const nRST_STOP: u32 = 9;
        pub const nRST_STDBY: u32 = 10;
        pub const nBOOT0: u32 = 11;
        pub const nBOOT1: u32 = 12;
        pub const VDDA_MONITOR: u32 = 13;
        pub const RAM_PARITY_CHECK: u32 = 14;
        pub const BOOT_SEL: u32 = 15;
        pub const Data0: u32 = 16;
        pub const Data1: u32 = 24;
    }
    pub mod wrpr {
        pub const WRP: u32 = 0;
    }
}
