// DO NOT EDIT. This was generated by svd2rusty
//! This module provides definitions for various hardware registers and their fields.

#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

pub mod GPIO {
    pub mod moder {
        pub const MODER15: u8 = 30;
        pub const MODER14: u8 = 28;
        pub const MODER13: u8 = 26;
        pub const MODER12: u8 = 24;
        pub const MODER11: u8 = 22;
        pub const MODER10: u8 = 20;
        pub const MODER9: u8 = 18;
        pub const MODER8: u8 = 16;
        pub const MODER7: u8 = 14;
        pub const MODER6: u8 = 12;
        pub const MODER5: u8 = 10;
        pub const MODER4: u8 = 8;
        pub const MODER3: u8 = 6;
        pub const MODER2: u8 = 4;
        pub const MODER1: u8 = 2;
        pub const MODER0: u8 = 0;
    }
    pub mod otyper {
        pub const OT15: u8 = 15;
        pub const OT14: u8 = 14;
        pub const OT13: u8 = 13;
        pub const OT12: u8 = 12;
        pub const OT11: u8 = 11;
        pub const OT10: u8 = 10;
        pub const OT9: u8 = 9;
        pub const OT8: u8 = 8;
        pub const OT7: u8 = 7;
        pub const OT6: u8 = 6;
        pub const OT5: u8 = 5;
        pub const OT4: u8 = 4;
        pub const OT3: u8 = 3;
        pub const OT2: u8 = 2;
        pub const OT1: u8 = 1;
        pub const OT0: u8 = 0;
    }
    pub mod ospeedr {
        pub const OSPEEDR15: u8 = 30;
        pub const OSPEEDR14: u8 = 28;
        pub const OSPEEDR13: u8 = 26;
        pub const OSPEEDR12: u8 = 24;
        pub const OSPEEDR11: u8 = 22;
        pub const OSPEEDR10: u8 = 20;
        pub const OSPEEDR9: u8 = 18;
        pub const OSPEEDR8: u8 = 16;
        pub const OSPEEDR7: u8 = 14;
        pub const OSPEEDR6: u8 = 12;
        pub const OSPEEDR5: u8 = 10;
        pub const OSPEEDR4: u8 = 8;
        pub const OSPEEDR3: u8 = 6;
        pub const OSPEEDR2: u8 = 4;
        pub const OSPEEDR1: u8 = 2;
        pub const OSPEEDR0: u8 = 0;
    }
    pub mod pupdr {
        pub const PUPDR15: u8 = 30;
        pub const PUPDR14: u8 = 28;
        pub const PUPDR13: u8 = 26;
        pub const PUPDR12: u8 = 24;
        pub const PUPDR11: u8 = 22;
        pub const PUPDR10: u8 = 20;
        pub const PUPDR9: u8 = 18;
        pub const PUPDR8: u8 = 16;
        pub const PUPDR7: u8 = 14;
        pub const PUPDR6: u8 = 12;
        pub const PUPDR5: u8 = 10;
        pub const PUPDR4: u8 = 8;
        pub const PUPDR3: u8 = 6;
        pub const PUPDR2: u8 = 4;
        pub const PUPDR1: u8 = 2;
        pub const PUPDR0: u8 = 0;
    }
    pub mod idr {
        pub const IDR15: u8 = 15;
        pub const IDR14: u8 = 14;
        pub const IDR13: u8 = 13;
        pub const IDR12: u8 = 12;
        pub const IDR11: u8 = 11;
        pub const IDR10: u8 = 10;
        pub const IDR9: u8 = 9;
        pub const IDR8: u8 = 8;
        pub const IDR7: u8 = 7;
        pub const IDR6: u8 = 6;
        pub const IDR5: u8 = 5;
        pub const IDR4: u8 = 4;
        pub const IDR3: u8 = 3;
        pub const IDR2: u8 = 2;
        pub const IDR1: u8 = 1;
        pub const IDR0: u8 = 0;
    }
    pub mod odr {
        pub const ODR15: u8 = 15;
        pub const ODR14: u8 = 14;
        pub const ODR13: u8 = 13;
        pub const ODR12: u8 = 12;
        pub const ODR11: u8 = 11;
        pub const ODR10: u8 = 10;
        pub const ODR9: u8 = 9;
        pub const ODR8: u8 = 8;
        pub const ODR7: u8 = 7;
        pub const ODR6: u8 = 6;
        pub const ODR5: u8 = 5;
        pub const ODR4: u8 = 4;
        pub const ODR3: u8 = 3;
        pub const ODR2: u8 = 2;
        pub const ODR1: u8 = 1;
        pub const ODR0: u8 = 0;
    }
    pub mod bsrr {
        pub const BR15: u8 = 31;
        pub const BR14: u8 = 30;
        pub const BR13: u8 = 29;
        pub const BR12: u8 = 28;
        pub const BR11: u8 = 27;
        pub const BR10: u8 = 26;
        pub const BR9: u8 = 25;
        pub const BR8: u8 = 24;
        pub const BR7: u8 = 23;
        pub const BR6: u8 = 22;
        pub const BR5: u8 = 21;
        pub const BR4: u8 = 20;
        pub const BR3: u8 = 19;
        pub const BR2: u8 = 18;
        pub const BR1: u8 = 17;
        pub const BR0: u8 = 16;
        pub const BS15: u8 = 15;
        pub const BS14: u8 = 14;
        pub const BS13: u8 = 13;
        pub const BS12: u8 = 12;
        pub const BS11: u8 = 11;
        pub const BS10: u8 = 10;
        pub const BS9: u8 = 9;
        pub const BS8: u8 = 8;
        pub const BS7: u8 = 7;
        pub const BS6: u8 = 6;
        pub const BS5: u8 = 5;
        pub const BS4: u8 = 4;
        pub const BS3: u8 = 3;
        pub const BS2: u8 = 2;
        pub const BS1: u8 = 1;
        pub const BS0: u8 = 0;
    }
    pub mod lckr {
        pub const LCKK: u8 = 16;
        pub const LCK15: u8 = 15;
        pub const LCK14: u8 = 14;
        pub const LCK13: u8 = 13;
        pub const LCK12: u8 = 12;
        pub const LCK11: u8 = 11;
        pub const LCK10: u8 = 10;
        pub const LCK9: u8 = 9;
        pub const LCK8: u8 = 8;
        pub const LCK7: u8 = 7;
        pub const LCK6: u8 = 6;
        pub const LCK5: u8 = 5;
        pub const LCK4: u8 = 4;
        pub const LCK3: u8 = 3;
        pub const LCK2: u8 = 2;
        pub const LCK1: u8 = 1;
        pub const LCK0: u8 = 0;
    }
    pub mod afrl {
        pub const AFRL7: u8 = 28;
        pub const AFRL6: u8 = 24;
        pub const AFRL5: u8 = 20;
        pub const AFRL4: u8 = 16;
        pub const AFRL3: u8 = 12;
        pub const AFRL2: u8 = 8;
        pub const AFRL1: u8 = 4;
        pub const AFRL0: u8 = 0;
    }
    pub mod afrh {
        pub const AFRH15: u8 = 28;
        pub const AFRH14: u8 = 24;
        pub const AFRH13: u8 = 20;
        pub const AFRH12: u8 = 16;
        pub const AFRH11: u8 = 12;
        pub const AFRH10: u8 = 8;
        pub const AFRH9: u8 = 4;
        pub const AFRH8: u8 = 0;
    }
    pub mod brr {
        pub const BR0: u8 = 0;
        pub const BR1: u8 = 1;
        pub const BR2: u8 = 2;
        pub const BR3: u8 = 3;
        pub const BR4: u8 = 4;
        pub const BR5: u8 = 5;
        pub const BR6: u8 = 6;
        pub const BR7: u8 = 7;
        pub const BR8: u8 = 8;
        pub const BR9: u8 = 9;
        pub const BR10: u8 = 10;
        pub const BR11: u8 = 11;
        pub const BR12: u8 = 12;
        pub const BR13: u8 = 13;
        pub const BR14: u8 = 14;
        pub const BR15: u8 = 15;
    }
}

pub mod WWDG {
    pub mod cr {
        pub const WDGA: u8 = 7;
        pub const T: u8 = 0;
    }
    pub mod cfr {
        pub const EWI: u8 = 9;
        pub const WDGTB: u8 = 7;
        pub const W: u8 = 0;
    }
    pub mod sr {
        pub const EWIF: u8 = 0;
    }
}

pub mod RCC {
    pub mod cr {
        pub const HSION: u8 = 0;
        pub const HSIRDY: u8 = 1;
        pub const HSITRIM: u8 = 3;
        pub const HSICAL: u8 = 8;
        pub const HSEON: u8 = 16;
        pub const HSERDY: u8 = 17;
        pub const HSEBYP: u8 = 18;
        pub const CSSON: u8 = 19;
        pub const PLLON: u8 = 24;
        pub const PLLRDY: u8 = 25;
    }
    pub mod cfgr {
        pub const SW: u8 = 0;
        pub const SWS: u8 = 2;
        pub const HPRE: u8 = 4;
        pub const PPRE: u8 = 8;
        pub const ADCPRE: u8 = 14;
        pub const PLLSRC: u8 = 15;
        pub const PLLXTPRE: u8 = 17;
        pub const PLLMUL: u8 = 18;
        pub const MCO: u8 = 24;
        pub const MCOPRE: u8 = 28;
        pub const PLLNODIV: u8 = 31;
    }
    pub mod cir {
        pub const LSIRDYF: u8 = 0;
        pub const LSERDYF: u8 = 1;
        pub const HSIRDYF: u8 = 2;
        pub const HSERDYF: u8 = 3;
        pub const PLLRDYF: u8 = 4;
        pub const HSI14RDYF: u8 = 5;
        pub const HSI48RDYF: u8 = 6;
        pub const CSSF: u8 = 7;
        pub const LSIRDYIE: u8 = 8;
        pub const LSERDYIE: u8 = 9;
        pub const HSIRDYIE: u8 = 10;
        pub const HSERDYIE: u8 = 11;
        pub const PLLRDYIE: u8 = 12;
        pub const HSI14RDYE: u8 = 13;
        pub const HSI48RDYIE: u8 = 14;
        pub const LSIRDYC: u8 = 16;
        pub const LSERDYC: u8 = 17;
        pub const HSIRDYC: u8 = 18;
        pub const HSERDYC: u8 = 19;
        pub const PLLRDYC: u8 = 20;
        pub const HSI14RDYC: u8 = 21;
        pub const HSI48RDYC: u8 = 22;
        pub const CSSC: u8 = 23;
    }
    pub mod apb2rstr {
        pub const SYSCFGRST: u8 = 0;
        pub const ADCRST: u8 = 9;
        pub const TIM1RST: u8 = 11;
        pub const SPI1RST: u8 = 12;
        pub const USART1RST: u8 = 14;
        pub const TIM15RST: u8 = 16;
        pub const TIM16RST: u8 = 17;
        pub const TIM17RST: u8 = 18;
        pub const DBGMCURST: u8 = 22;
    }
    pub mod apb1rstr {
        pub const TIM2RST: u8 = 0;
        pub const TIM3RST: u8 = 1;
        pub const TIM6RST: u8 = 4;
        pub const TIM7RST: u8 = 5;
        pub const TIM14RST: u8 = 8;
        pub const WWDGRST: u8 = 11;
        pub const SPI2RST: u8 = 14;
        pub const USART2RST: u8 = 17;
        pub const USART3RST: u8 = 18;
        pub const USART4RST: u8 = 19;
        pub const I2C1RST: u8 = 21;
        pub const I2C2RST: u8 = 22;
        pub const USBRST: u8 = 23;
        pub const CANRST: u8 = 25;
        pub const CRSRST: u8 = 27;
        pub const PWRRST: u8 = 28;
        pub const DACRST: u8 = 29;
        pub const CECRST: u8 = 30;
    }
    pub mod ahbenr {
        pub const DMA1EN: u8 = 0;
        pub const SRAMEN: u8 = 2;
        pub const FLITFEN: u8 = 4;
        pub const CRCEN: u8 = 6;
        pub const IOPAEN: u8 = 17;
        pub const IOPBEN: u8 = 18;
        pub const IOPCEN: u8 = 19;
        pub const IOPDEN: u8 = 20;
        pub const IOPFEN: u8 = 22;
        pub const TSCEN: u8 = 24;
    }
    pub mod apb2enr {
        pub const SYSCFGEN: u8 = 0;
        pub const ADCEN: u8 = 9;
        pub const TIM1EN: u8 = 11;
        pub const SPI1EN: u8 = 12;
        pub const USART1EN: u8 = 14;
        pub const TIM15EN: u8 = 16;
        pub const TIM16EN: u8 = 17;
        pub const TIM17EN: u8 = 18;
        pub const DBGMCUEN: u8 = 22;
    }
    pub mod apb1enr {
        pub const TIM2EN: u8 = 0;
        pub const TIM3EN: u8 = 1;
        pub const TIM6EN: u8 = 4;
        pub const TIM7EN: u8 = 5;
        pub const TIM14EN: u8 = 8;
        pub const WWDGEN: u8 = 11;
        pub const SPI2EN: u8 = 14;
        pub const USART2EN: u8 = 17;
        pub const USART3EN: u8 = 18;
        pub const USART4EN: u8 = 19;
        pub const I2C1EN: u8 = 21;
        pub const I2C2EN: u8 = 22;
        pub const USBRST: u8 = 23;
        pub const CANEN: u8 = 25;
        pub const CRSEN: u8 = 27;
        pub const PWREN: u8 = 28;
        pub const DACEN: u8 = 29;
        pub const CECEN: u8 = 30;
    }
    pub mod bdcr {
        pub const LSEON: u8 = 0;
        pub const LSERDY: u8 = 1;
        pub const LSEBYP: u8 = 2;
        pub const LSEDRV: u8 = 3;
        pub const RTCSEL: u8 = 8;
        pub const RTCEN: u8 = 15;
        pub const BDRST: u8 = 16;
    }
    pub mod csr {
        pub const LSION: u8 = 0;
        pub const LSIRDY: u8 = 1;
        pub const RMVF: u8 = 24;
        pub const OBLRSTF: u8 = 25;
        pub const PINRSTF: u8 = 26;
        pub const PORRSTF: u8 = 27;
        pub const SFTRSTF: u8 = 28;
        pub const IWDGRSTF: u8 = 29;
        pub const WWDGRSTF: u8 = 30;
        pub const LPWRRSTF: u8 = 31;
    }
    pub mod ahbrstr {
        pub const IOPARST: u8 = 17;
        pub const IOPBRST: u8 = 18;
        pub const IOPCRST: u8 = 19;
        pub const IOPDRST: u8 = 20;
        pub const IOPFRST: u8 = 22;
        pub const TSCRST: u8 = 24;
    }
    pub mod cfgr2 {
        pub const PREDIV: u8 = 0;
    }
    pub mod cfgr3 {
        pub const USART1SW: u8 = 0;
        pub const I2C1SW: u8 = 4;
        pub const CECSW: u8 = 6;
        pub const USBSW: u8 = 7;
        pub const ADCSW: u8 = 8;
        pub const USART2SW: u8 = 16;
    }
    pub mod cr2 {
        pub const HSI14ON: u8 = 0;
        pub const HSI14RDY: u8 = 1;
        pub const HSI14DIS: u8 = 2;
        pub const HSI14TRIM: u8 = 3;
        pub const HSI14CAL: u8 = 8;
        pub const HSI48ON: u8 = 16;
        pub const HSI48RDY: u8 = 17;
        pub const HSI48CAL: u8 = 24;
    }
}

pub mod USART {
    pub mod cr1 {
        pub const UE: u8 = 0;
        pub const UESM: u8 = 1;
        pub const RE: u8 = 2;
        pub const TE: u8 = 3;
        pub const IDLEIE: u8 = 4;
        pub const RXNEIE: u8 = 5;
        pub const TCIE: u8 = 6;
        pub const TXEIE: u8 = 7;
        pub const PEIE: u8 = 8;
        pub const PS: u8 = 9;
        pub const PCE: u8 = 10;
        pub const WAKE: u8 = 11;
        pub const M: u8 = 12;
        pub const MME: u8 = 13;
        pub const CMIE: u8 = 14;
        pub const OVER8: u8 = 15;
        pub const DEDT: u8 = 16;
        pub const DEAT: u8 = 21;
        pub const RTOIE: u8 = 26;
        pub const EOBIE: u8 = 27;
        pub const M1: u8 = 28;
    }
    pub mod cr2 {
        pub const ADD4: u8 = 28;
        pub const ADD0: u8 = 24;
        pub const RTOEN: u8 = 23;
        pub const ABRMOD: u8 = 21;
        pub const ABREN: u8 = 20;
        pub const MSBFIRST: u8 = 19;
        pub const DATAINV: u8 = 18;
        pub const TXINV: u8 = 17;
        pub const RXINV: u8 = 16;
        pub const SWAP: u8 = 15;
        pub const LINEN: u8 = 14;
        pub const STOP: u8 = 12;
        pub const CLKEN: u8 = 11;
        pub const CPOL: u8 = 10;
        pub const CPHA: u8 = 9;
        pub const LBCL: u8 = 8;
        pub const LBDIE: u8 = 6;
        pub const LBDL: u8 = 5;
        pub const ADDM7: u8 = 4;
    }
    pub mod cr3 {
        pub const WUFIE: u8 = 22;
        pub const WUS: u8 = 20;
        pub const SCARCNT: u8 = 17;
        pub const DEP: u8 = 15;
        pub const DEM: u8 = 14;
        pub const DDRE: u8 = 13;
        pub const OVRDIS: u8 = 12;
        pub const ONEBIT: u8 = 11;
        pub const CTSIE: u8 = 10;
        pub const CTSE: u8 = 9;
        pub const RTSE: u8 = 8;
        pub const DMAT: u8 = 7;
        pub const DMAR: u8 = 6;
        pub const SCEN: u8 = 5;
        pub const NACK: u8 = 4;
        pub const HDSEL: u8 = 3;
        pub const IRLP: u8 = 2;
        pub const IREN: u8 = 1;
        pub const EIE: u8 = 0;
    }
    pub mod brr {
        pub const DIV_Mantissa: u8 = 4;
        pub const DIV_Fraction: u8 = 0;
    }
    pub mod gtpr {
        pub const GT: u8 = 8;
        pub const PSC: u8 = 0;
    }
    pub mod rtor {
        pub const BLEN: u8 = 24;
        pub const RTO: u8 = 0;
    }
    pub mod rqr {
        pub const TXFRQ: u8 = 4;
        pub const RXFRQ: u8 = 3;
        pub const MMRQ: u8 = 2;
        pub const SBKRQ: u8 = 1;
        pub const ABRRQ: u8 = 0;
    }
    pub mod isr {
        pub const REACK: u8 = 22;
        pub const TEACK: u8 = 21;
        pub const WUF: u8 = 20;
        pub const RWU: u8 = 19;
        pub const SBKF: u8 = 18;
        pub const CMF: u8 = 17;
        pub const BUSY: u8 = 16;
        pub const ABRF: u8 = 15;
        pub const ABRE: u8 = 14;
        pub const EOBF: u8 = 12;
        pub const RTOF: u8 = 11;
        pub const CTS: u8 = 10;
        pub const CTSIF: u8 = 9;
        pub const LBDF: u8 = 8;
        pub const TXE: u8 = 7;
        pub const TC: u8 = 6;
        pub const RXNE: u8 = 5;
        pub const IDLE: u8 = 4;
        pub const ORE: u8 = 3;
        pub const NF: u8 = 2;
        pub const FE: u8 = 1;
        pub const PE: u8 = 0;
    }
    pub mod icr {
        pub const WUCF: u8 = 20;
        pub const CMCF: u8 = 17;
        pub const EOBCF: u8 = 12;
        pub const RTOCF: u8 = 11;
        pub const CTSCF: u8 = 9;
        pub const LBDCF: u8 = 8;
        pub const TCCF: u8 = 6;
        pub const IDLECF: u8 = 4;
        pub const ORECF: u8 = 3;
        pub const NCF: u8 = 2;
        pub const FECF: u8 = 1;
        pub const PECF: u8 = 0;
    }
    pub mod rdr {
        pub const RDR: u8 = 0;
    }
    pub mod tdr {
        pub const TDR: u8 = 0;
    }
}

pub mod FLASH {
    pub mod acr {
        pub const LATENCY: u8 = 0;
        pub const PRFTBE: u8 = 4;
        pub const PRFTBS: u8 = 5;
    }
    pub mod keyr {
        pub const FKEYR: u8 = 0;
    }
    pub mod optkeyr {
        pub const OPTKEYR: u8 = 0;
    }
    pub mod sr {
        pub const EOP: u8 = 5;
        pub const WRPRT: u8 = 4;
        pub const PGERR: u8 = 2;
        pub const BSY: u8 = 0;
    }
    pub mod cr {
        pub const FORCE_OPTLOAD: u8 = 13;
        pub const EOPIE: u8 = 12;
        pub const ERRIE: u8 = 10;
        pub const OPTWRE: u8 = 9;
        pub const LOCK: u8 = 7;
        pub const STRT: u8 = 6;
        pub const OPTER: u8 = 5;
        pub const OPTPG: u8 = 4;
        pub const MER: u8 = 2;
        pub const PER: u8 = 1;
        pub const PG: u8 = 0;
    }
    pub mod ar {
        pub const FAR: u8 = 0;
    }
    pub mod obr {
        pub const OPTERR: u8 = 0;
        pub const RDPRT: u8 = 1;
        pub const WDG_SW: u8 = 8;
        pub const nRST_STOP: u8 = 9;
        pub const nRST_STDBY: u8 = 10;
        pub const nBOOT0: u8 = 11;
        pub const nBOOT1: u8 = 12;
        pub const VDDA_MONITOR: u8 = 13;
        pub const RAM_PARITY_CHECK: u8 = 14;
        pub const BOOT_SEL: u8 = 15;
        pub const Data0: u8 = 16;
        pub const Data1: u8 = 24;
    }
    pub mod wrpr {
        pub const WRP: u8 = 0;
    }
}

#[repr(C)]
pub struct GpioReg {
    pub moder: u32,
    pub otyper: u32,
    pub ospeedr: u32,
    pub pupdr: u32,
    pub idr: u32,
    pub odr: u32,
    pub bsrr: u32,
    pub lckr: u32,
    pub afrl: u32,
    pub afrh: u32,
    pub brr: u32,
}

#[repr(C)]
pub struct WwdgReg {
    pub cr: u32,
    pub cfr: u32,
    pub sr: u32,
}

#[repr(C)]
pub struct RccReg {
    pub cr: u32,
    pub cfgr: u32,
    pub cir: u32,
    pub apb2rstr: u32,
    pub apb1rstr: u32,
    pub ahbenr: u32,
    pub apb2enr: u32,
    pub apb1enr: u32,
    pub bdcr: u32,
    pub csr: u32,
    pub ahbrstr: u32,
    pub cfgr2: u32,
    pub cfgr3: u32,
    pub cr2: u32,
}

#[repr(C)]
pub struct UsartReg {
    pub cr1: u32,
    pub cr2: u32,
    pub cr3: u32,
    pub brr: u32,
    pub gtpr: u32,
    pub rtor: u32,
    pub rqr: u32,
    pub isr: u32,
    pub icr: u32,
    pub rdr: u32,
    pub tdr: u32,
}

#[repr(C)]
pub struct FlashReg {
    pub acr: u32,
    pub keyr: u32,
    pub optkeyr: u32,
    pub sr: u32,
    pub cr: u32,
    pub ar: u32,
    reserved1: u32,
    pub obr: u32,
    pub wrpr: u32,
}

pub const GPIOB: *mut GpioReg = 0x48000400 as *mut GpioReg;

pub const GPIOA: *mut GpioReg = 0x48000000 as *mut GpioReg;

pub const WWDG: *mut WwdgReg = 0x40002C00 as *mut WwdgReg;

pub const RCC: *mut RccReg = 0x40021000 as *mut RccReg;

pub const USART1: *mut UsartReg = 0x40013800 as *mut UsartReg;

pub const USART2: *mut UsartReg = 0x40004400 as *mut UsartReg;

pub const FLASH: *mut FlashReg = 0x40022000 as *mut FlashReg;
