name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Cortex-M0 dependencies
        run: rustup target add thumbv6m-none-eabi
      - name: Install Coretex-M4 dependencies
        run: rustup target add thumbv7em-none-eabihf
      - name: Build x86 and run-sim
        run: make run-sim
      - name: Build arm hactar12
        run: make build
      - name: Build arm hactar12 mgmt
        run: make build-mgmt
      - name: Run tests
        run: make test
